
ARG GO_DOCKER_VERSION=1.23

FROM golang:${GO_DOCKER_VERSION}-alpine AS builder

ENV APP_DIR=/app \
    APP_ENV=production \
    APP_LISTEN_PORT=8080

WORKDIR $APP_DIR/cmd/app

COPY . $APP_DIR

RUN go build -o app main.go

FROM alpine:3.20.3

WORKDIR /app

COPY --from=builder /app/cmd/app/app .

EXPOSE 8080

CMD ["./app"]