ARG GO_DOCKER_VERSION=1.23.4

FROM golang:${GO_DOCKER_VERSION}-alpine AS builder

ENV APP_SRC=/go/src \
    APP_BIN=/go/bin \
    APP_ENV=development \
    APP_LISTEN_PORT=8080

WORKDIR ${APP_SRC}

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -o ../bin ${APP_SRC}/cmd/app/main.go

EXPOSE ${APP_LISTEN_PORT}

WORKDIR ../
CMD ["./bin/main"]
#CMD ["tail", "-f", "/dev/null"]